version: '3'

services:
  kong-database:
    build: ./Cassandra
    container_name: kong-database
    volumes:
      - ./db-kong:/var/lib/cassandra
    ports:
      - 9042:9042

  kong:
    build: ./Kong
    container_name: kong
    depends_on: 
      - Cassandra
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    command: ["kong", "start"]

  BookManager:
          build: ./BookManager
    container_name: BookManager-Application
    volumes:
      - ./BookManager:/usr/src/app
    ports:
      - 27015:80