echo -e 'configure-route.sh  [Options... ]'
echo -e ' K         \t Kong Server Host With Port (e.g. http://KongServer.com:8001 )'
echo -e ' t         \t Resource Type (e.g. Route) - Default Value is \"service\"'
echo -e '*n         \t Resource Name, this will compose the Path at admin API'
echo -e '*u         \t Resource URL (e.g. https://httpbin.org)'
echo -e ' m         \t Acceptable Methos (e.g. "GET,POST,PUT,DELETE")'
echo -e ' p         \t Available Paths for Resource (Such as "/headers")'
echo -e ' c         \t Consumer Name'
echo -e ' k         \t Basic Auth Consumer'
echo -e ' b        \t Black List Flag to ACL Control (Default is WhiteList)'
echo -e ' g         \t Group Name for ACL Control'
echo -e ' l         \t Server to Log Requests (e.g. http://logStash.myCompany/)'
echo -e ' P         \t LogServe Port'
echo -e " * = Necessary Field"